# Generated by Django 3.1.3 on 2020-11-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pup_data',
            new_name='pub_date',
        ),
    ]
